name: status

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - run: pnpm lint
        shell: bash
